### ISSUE TITLE
hpcli fail case.

### ISSUE THREAD

**Issue by Sumching** [megvii-research/hpargparse#16]
`src.py`

```
 #!/usr/bin/env python3
 from hpman.m import hp, _
 hp('batch_size', 128)
 _('test', 111)
```

`hpcli src.py`

It only outputs:

```shell
test: 111
```

**Comment by zxytim** [comment]
This is the intended behavior. 

`HyperParameterManager` object imported from `hpman.m` corresponds to different placeholder strings. They are independent objects and operate independently.

`hpcli` uses "_" as the default placeholder. You can change this behavior using `--placeholder`:
```bash
$ hpcli --placeholder hp src.py
batch_size: 128
```
